services:
  assistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config/data:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

  wyoming-whisper:
    image: rhasspy/wyoming-whisper:latest
    command: --model medium --language pt
    volumes:
      - ./wyoming-whisper/data:/data
    ports:
      - 10300:10300
    restart: unless-stopped

  wyoming-piper:
    image: rhasspy/wyoming-piper:latest
    command: --voice en_US-bmo_voice --data-dir /data --length-scale 0.85 --noise-scale 0.3 --noise-w-scale 0.3
    volumes:
      - ./wyoming-piper/data:/data
      - ./wyoming-piper/data/voices.json:/usr/src/wyoming_piper/voices.json:ro
    ports:
      - 10200:10200
    restart: unless-stopped

  linux-voice-assistant:
    image: ghcr.io/ohf-voice/linux-voice-assistant:latest
    environment:
      - HA_HOST=127.0.0.1
      - HA_PORT=8123
      - HA_TOKEN=${HA_TOKEN}
      - MICROPHONE_DEVICE=default
      - SPEAKER_DEVICE=default
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    volumes:
      - ./linux-voice-assistant/wakewords/bmo.json:/app/wakewords/bmo.json
      - ./linux-voice-assistant/wakewords/bmo.tflite:/app/wakewords/bmo.tflite
      - /run/user/1000/pulse:/run/user/1000/pulse
    devices:
      - /dev/snd:/dev/snd
    network_mode: host
    restart: unless-stopped

  bmo-face:
    build: ./bmo-face
    environment:
      - HA_TOKEN=${HA_TOKEN}
    ports:
      - 8888:80
    restart: unless-stopped

  # pihole:
  #   image: pihole/pihole:latest
  #   ports:
  #     - "53:53/tcp"
  #     - "53:53/udp"
  #     - "8080:80/tcp"
  #   environment:
  #     TZ: 'America/Sao_Paulo'
  #     FTLCONF_webserver_api_password: '123'
  #     FTLCONF_dns_listeningMode: 'ALL'
  #   volumes:
  #     - './etc-pihole:/etc/pihole'
  #   restart: unless-stopped